dist: xenial
sudo: required

language: go
go:
  - 1.12.x


cache:
  directories:
    # https://docs.travis-ci.com/user/caching/
    # "If you store archives larger than a few hundred megabytes
    # in the cache, it is unlikely that you’ll see a big
    # speed improvement".
    #
    # this list of directories seems to speedup things:
    #
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/.terraform.d/plugins

#branches:
#  only:
#    - master

env:
  global:
    # Force-enable Go modules. Also force go to use the code in vendor/
    # These will both be unnecessary when Go 1.13 lands.
    - GO111MODULE=on
    - TF_ACC=true
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
    - CI=travis
    - IS_CI=true
    - E2E_CLEANUP=true
  matrix:
    # run tests in two different configurations: with flannel and with weave
    - TF_VAR_cni=flannel
    - TF_VAR_cni=weave

before_install:
  - make ci-setup

# NOTE: use this `sudo .. su` trick in order to use things like
#       the `usermod -a -G lxd` we did on the `before_install`
script:
  - sudo -E su $USER -c "make ci-tests"

after_failure:
  - sudo journalctl -e

